#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "nexus" {
  source = "./module-nexus"

  customer  = var.customer
  disk_size = 20
  env       = var.env
  extra_tags = {
    demo = true
  }
  instance_type  = "t3.micro"
  keypair_public = var.keypair_public
  project        = var.project
  public_subnets = "${data.terraform_remote_state.infra.outputs.public_subnets}"
  vpc_id         = "${data.terraform_remote_state.infra.outputs.vpc_id}"
}

