#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "website" {
  source = "./module-website"

  cloudfront_aliases = [
    "mydomain.com"
  ]
  cloudfront_certificate_arn = ""
  cloudfront_default_ttl     = 300
  cloudfront_max_ttl         = 604800
  cloudfront_min_ttl         = 0
  cloudfront_price_class     = "PriceClass_200"
  cors_allowed_headers = [
    "*"
  ]
  cors_allowed_methods = [
    "GET"
  ]
  cors_allowed_origins = [

  ]
  cors_expose_headers = [
    "ETag"
  ]
  cors_max_age_seconds = 3600
  customer             = var.customer
  env                  = var.env
  extra_tags = {
  }
  project        = var.project
  s3_bucket_name = ""
}

